sudo: required
cache:
  - apt

language: python
matrix:
    include:
        - python: 3.6
          env: TEST_MODE=PEP8
          dist: trusty
        - python: 3.7
          dist: bionic
          env: INPUT_IMAGE=https://github.com/reshalfahsi/GGB/raw/master/docs/img/leukocytes.png
install:
  - pip install --upgrade pip
  - pip install -e .[tests]

# command to run tests
script:
  - echo -e "Running tests..."
  - if [[ "$TEST_MODE" == "PEP8" ]]; then
       PYTHONPATH=$PWD:$PYTHONPATH py.test --pep8 -m pep8 -n0;
    else
       pytest --tb=short -q --cov-report term-missing --cov=. tests/;
       ggb $INPUT_IMAGE
       coverage xml;
       coverage report -m;
       codecov;
    fi
after_success:
  - echo -e "Testing finished..."
