sudo: required
dist: bionic
language: python
matrix:
    include:
        - python: 3.6
          env: TEST_MODE=PEP8
        - python: 3.6
        - python: 3.7
        - python: 3.8
install:
  - pip install numpy Pillow six
  - pip install --upgrade pip
  - pip install opencv-python
  - pip install -e .[tests]

# command to run tests
script:
  - echo -e "Running tests..."
  - if [[ "$TEST_MODE" == "PEP8" ]]; then
       PYTHONPATH=$PWD:$PYTHONPATH py.test --pep8;
    else
       PYTHONPATH=$PWD:$PYTHONPATH py.test tests/;
    fi
after_success:
  - coveralls
