sudo: required
cache:
  - apt

language: python
matrix:
    include:
        - python: 3.6
          env: TEST_MODE=PEP8
          dist: trusty
        - python: 3.6
          dist: bionic
        - python: 3.7
          dist: bionic
install:
  - pip install codecov
  - pip install numpy Pillow six
  - pip install --upgrade pip
  - pip install opencv-python
  - pip install -e .[tests]

# command to run tests
script:
  - echo -e "Running tests..."
  - if [[ "$TEST_MODE" == "PEP8" ]]; then
       PYTHONPATH=$PWD:$PYTHONPATH py.test --pep8 -m pep8 -n0;
    else
       PYTHONPATH=$PWD:$PYTHONPATH py.test tests/;
       coverage run -m pytest;
    fi
after_success:
  - codecov
